# Generated by Django 6.0.2 on 2026-05-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_add_restaurant_role_and_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='post_code',
        ),
    ]
