# Generated by Django 6.0.2 on 2026-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_loginattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='mainApp_log_ip_addr_78cbb8_idx',
            old_name='mainapp_log_ip_addr_idx',
        ),
    ]
