# Generated by Django 6.0.2 on 2026-05-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('ml', 'Millilitres (ml)'), ('litre', 'Litre (L)'), ('dozen', 'Dozen'), ('half dozen', 'Half Dozen'), ('each', 'Each'), ('bunch', 'Bunch'), ('500g', '500 grams'), ('250g', '250 grams'), ('1kg', '1 kilogram'), ('jar', 'Jar'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('pair', 'Pair'), ('piece', 'Piece')], help_text='e.g., kg, dozen, each', max_length=50),
        ),
    ]
