# Generated by Django 6.0.2 on 2026-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo_image_url',
            field=models.URLField(blank=True, help_text='Auto-detected demo image URL from bucket (set by Celery task)', max_length=500),
        ),
    ]
